server:
   port: 8083
spring:
  application:
    name: recommendation-service

  cloud:
    stream:
      bindings:
        input:
          destination: orderevents
#  data:
#   elasticsearch:
#    cluster-nodes: localhost:9300
  
 
 
      
      
        



